name: learn-github-actions
on:
  - push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world-action
  build:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
        swift-version:
          - "5.5"
          - "5.0"
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1.11.0
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: test
        run: swift test
