name: learn-github-actions
on:
  - push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world-action
      - uses: fwal/setup-swift@v1.11.0
        with:
          swift-version: 5.5.2
      - run: swift build
